Class R.Test.Production Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="R.Test.Production" TestingEnabled="true" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="R.Test.Process" Category="" ClassName="R.Test.Process" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
  <Item Name="R.Ens.Operation" Category="" ClassName="R.Ens.Operation" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}

